from building import *

# get current directory
cwd     = GetCurrentDir()
# The set of source files associated with this SConscript file.
src     = Glob('src/*.c')
src    += Glob('port/*.c')
src    += Glob('plugins/flash/*.c')

path    = [cwd + '/inc']
path   += [cwd + '/plugins/flash']

group = DefineGroup('EasyLogger', src, depend = ['RT_USING_EasyLogger'], CPPPATH = path)

Return('group')
